# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTunesServices' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTunesServices

  target 'iTunesServicesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iTunesServicesUITests' do
    # Pods for testing
  end

pod 'Alamofire', '~> 5.4'


end
